import type { MenuItemDTO, CartItem, ComboMealDTO, CategoryDTO } from "@/lib/types";

export const mockMenuItems: MenuItemDTO[] = [
  {
    id: 1,
    name: "Big Mac",
    description: "Two all-beef patties, special sauce",
    price: 5.99,
    imageUrl: null,
    available: true,
    categoryId: 1,
    categoryName: "Burgers",
    aliases: ["bigmac", "big mac"],
    customizations: [
      { id: 1, name: "Extra Patty", priceExtra: 1.5 },
      { id: 2, name: "No Pickles", priceExtra: 0 },
    ],
  },
  {
    id: 2,
    name: "Quarter Pounder with Cheese",
    description: "Quarter pound of beef with cheese",
    price: 6.49,
    imageUrl: null,
    available: true,
    categoryId: 1,
    categoryName: "Burgers",
    aliases: ["quarter pounder", "qp"],
    customizations: [],
  },
  {
    id: 3,
    name: "McChicken",
    description: "Crispy chicken sandwich",
    price: 3.99,
    imageUrl: null,
    available: true,
    categoryId: 2,
    categoryName: "Chicken & Fish",
    aliases: ["mc chicken"],
    customizations: [],
  },
  {
    id: 4,
    name: "Medium Fries",
    description: "Medium French fries",
    price: 3.49,
    imageUrl: null,
    available: true,
    categoryId: 3,
    categoryName: "Fries",
    aliases: ["fries", "medium fries"],
    customizations: [],
  },
  {
    id: 5,
    name: "Medium Coke",
    description: "Coca-Cola",
    price: 2.49,
    imageUrl: null,
    available: true,
    categoryId: 4,
    categoryName: "Drinks",
    aliases: ["coke", "coca cola"],
    customizations: [],
  },
  {
    id: 6,
    name: "McFlurry with OREO Cookies",
    description: "Vanilla soft serve with OREO",
    price: 4.99,
    imageUrl: null,
    available: true,
    categoryId: 5,
    categoryName: "Desserts",
    aliases: ["mcflurry", "oreo mcflurry"],
    customizations: [],
  },
  {
    id: 7,
    name: "Chicken McNuggets (10 piece)",
    description: "10 piece chicken mcnuggets",
    price: 5.49,
    imageUrl: null,
    available: true,
    categoryId: 2,
    categoryName: "Chicken & Fish",
    aliases: ["nuggets", "mcnuggets", "10 piece nuggets"],
    customizations: [],
  },
  {
    id: 8,
    name: "Filet-O-Fish",
    description: "Fish filet sandwich",
    price: 5.29,
    imageUrl: null,
    available: false,
    categoryId: 2,
    categoryName: "Chicken & Fish",
    aliases: ["filet o fish", "fish sandwich"],
    customizations: [],
  },
];

export const mockCategories: CategoryDTO[] = [
  {
    id: 1,
    name: "Burgers",
    sortOrder: 1,
    items: mockMenuItems.filter((i) => i.categoryName === "Burgers"),
  },
  {
    id: 2,
    name: "Chicken & Fish",
    sortOrder: 2,
    items: mockMenuItems.filter((i) => i.categoryName === "Chicken & Fish"),
  },
  {
    id: 3,
    name: "Fries",
    sortOrder: 3,
    items: mockMenuItems.filter((i) => i.categoryName === "Fries"),
  },
  {
    id: 4,
    name: "Drinks",
    sortOrder: 4,
    items: mockMenuItems.filter((i) => i.categoryName === "Drinks"),
  },
  {
    id: 5,
    name: "Desserts",
    sortOrder: 5,
    items: mockMenuItems.filter((i) => i.categoryName === "Desserts"),
  },
];

export function makeCartItem(overrides: Partial<CartItem> & { menuItemId: number; name: string }): CartItem {
  return {
    id: `${overrides.menuItemId}-`,
    quantity: 1,
    unitPrice: 5.99,
    customizations: [],
    imageUrl: null,
    ...overrides,
  };
}

export const mockCombo: ComboMealDTO = {
  id: 1,
  name: "Big Mac Meal",
  description: "Big Mac with fries and drink",
  basePrice: 9.99,
  discount: 1.5,
  mainItemId: 1,
  defaultSideId: 4,
  defaultDrinkId: 5,
  available: true,
  popular: true,
  aliases: ["big mac meal", "big mac combo"],
};

export const mockCombos: ComboMealDTO[] = [
  mockCombo,
  {
    id: 2,
    name: "McChicken Meal",
    description: "McChicken with fries and drink",
    basePrice: 7.99,
    discount: 1.0,
    mainItemId: 3,
    defaultSideId: 4,
    defaultDrinkId: 5,
    available: true,
    popular: false,
    aliases: ["mcchicken meal"],
  },
];
